name:                hledupt
version:             0.1.0.0
github:              "githubuser/hledupt"
license:             AGPL-3
author:              "Grzegorz Milka"
maintainer:          "grzegorzmilka@gmail.com"
copyright:           "2020-2021 Grzegorz Milka"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gregorias/hledupt#readme>

dependencies:
- base >= 4.7 && < 5

# Some defaults recommended by https://kowainik.github.io/posts/2019-02-06-style-guide#default-extensions
# Also use Relude
default-extensions:
  BangPatterns
  DataKinds
  DeriveDataTypeable
  DeriveFoldable
  DeriveFunctor
  DeriveGeneric
  DeriveTraversable
  DerivingStrategies
  DerivingVia
  FlexibleContexts
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralisedNewtypeDeriving
  InstanceSigs
  LambdaCase
  MultiParamTypeClasses
  MultiWayIf
  NoImplicitPrelude
  NumericUnderscores
  OverloadedLabels
  OverloadedStrings
  PatternSynonyms
  QuasiQuotes
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeApplications
  TypeFamilies
  TypeOperators
  UnicodeSyntax
  ViewPatterns

# no-type-defaults, this is dangerous, but in terms of convenience it's so
# useful to use ExtendedDefaultRules that I keep it.
ghc-options:
  - -Wall
  - -Wcompat
  - -Wmissing-deriving-strategies
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-type-defaults
  - -Wno-partial-type-signatures

library:
  source-dirs: src
  dependencies:
  - Decimal
  - bytestring
  - cassava
  - containers
  - currency-codes
  - extra
  - hledger-lib >= 1.19
  - lens
  - lens-regex-pcre
  - megaparsec
  - mtl
  - parser-combinators
  - relude
  - safe
  - text
  - time
  - time-compat
  - transformers
  - unordered-containers
  - vector

executables:
  hledupt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - cli
    - hledupt
    - lens
    - megaparsec
    - relude
    - text
    - time

tests:
  hledupt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Spec
    dependencies:
    - Decimal
    - cassava
    - containers
    - hledger-lib
    - hledupt
    - hspec
    - hspec-expectations-pretty-diff
    - lens
    - megaparsec
    - neat-interpolation
    - parser-combinators
    - relude
    - replace-megaparsec
    - text
    - time
    - vector

  doctest:
    main:                DocTest.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is DocTest
    dependencies:
    - doctest
    - hledupt
    - relude
