name:                hledupt
version:             0.1.0.0
github:              "githubuser/hledupt"
license:             BSD3
author:              "Grzegorz Milka"
maintainer:          "grzegorzmilka@gmail.com"
copyright:           "2020 Grzegorz Milka"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gregorias/hledupt#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - Decimal
  - bytestring
  - cassava
  - either
  - hledger-lib >= 1.19
  - lens
  - megaparsec
  - mtl
  - safe
  - text
  - time
  - vector
  - parser-combinators
  - containers

executables:
  hledupt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledupt
    - cli
    - megaparsec
    - mtl
    - with-utf8

tests:
  hledupt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Decimal
    - cassava
    - containers
    - hledger-lib
    - hledupt
    - hspec
    - lens
    - megaparsec
    - parser-combinators
    - replace-megaparsec
    - text
    - time
