name:                hledupt
version:             0.1.0.0
github:              "githubuser/hledupt"
license:             AGPL-3
author:              "Grzegorz Milka"
maintainer:          "grzegorzmilka@gmail.com"
copyright:           "2020-2021 Grzegorz Milka"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gregorias/hledupt#readme>

dependencies:
- base >= 4.7 && < 5

# Defaults recommended by https://kowainik.github.io/posts/2019-02-06-style-guide#default-extensions
# Also use Relude
default-extensions:
  DerivingStrategies
  GeneralisedNewtypeDeriving
  InstanceSigs
  LambdaCase
  MultiWayIf
  NoImplicitPrelude
  NumericUnderscores
  ScopedTypeVariables
  TupleSections
  TypeApplications
  UnicodeSyntax

library:
  source-dirs: src
  dependencies:
  - Decimal
  - bytestring
  - cassava
  - containers
  - currency-codes
  - extra
  - hledger-lib >= 1.19
  - lens
  - lens-regex-pcre
  - megaparsec
  - mtl
  - parser-combinators
  - relude
  - safe
  - text
  - time
  - transformers
  - unordered-containers
  - vector

executables:
  hledupt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - cli
    - hledupt
    - lens
    - megaparsec
    - relude
    - text
    - time

tests:
  hledupt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Spec
    dependencies:
    - Decimal
    - cassava
    - containers
    - hledger-lib
    - hledupt
    - hspec
    - hspec-expectations-pretty-diff
    - lens
    - megaparsec
    - parser-combinators
    - relude
    - replace-megaparsec
    - text
    - time
    - vector
